@startuml
!theme plain

package "Algolios Network" {
    package algolio {
        [algolio.go]
        [algolio.puml]
        [algoliomock.go]
        [discovery.go]
        [dkg.go]
        [interaction.go]
        [interactionTypes.go]
        [learning.go]
        [logger.go]
        [network.go]
        [peer.go]
    }

    package circuit {
        [default.go]
    }

    package community {
        [community.go]
    }

    package cryptography {
        [circuit.go]
        [encryption_test.go]
        [keys.go]
    }

    package identity {
        [account.go]
        [address.go]
        [address_test.go]
    }

    package main {
        [transaction.go]
    }

    package utils {
        [chaincode.go]
        [config.go]
        [encryption.go]
    }

    package algocdm {
        [go.mod]
        [main.go]
    }

    [algolio.go] --> [dkg.go] : uses >
    [algolio.go] --> [network.go] : uses >
    [network.go] --> [peer.go] : uses >
    [dkg.go] --> [keys.go] : uses >
    [transaction.go] --> [community.go] : interacts >
    [community.go] --> [learning.go] : informs >
    [address.go] ..> [encryption.go] : encrypts >
}

@enduml
