// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.20.3
// source: pkg/network/protos/dkg_messages.proto

package netpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DKGDealMessage represents a DKG deal message
type DKGDealMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderId int32  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	DealData []byte `protobuf:"bytes,2,opt,name=deal_data,json=dealData,proto3" json:"deal_data,omitempty"` // The deal data, which is a serialized version of the pedersen.DistKeyShareDeal structure
}

func (x *DKGDealMessage) Reset() {
	*x = DKGDealMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_network_protos_dkg_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DKGDealMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DKGDealMessage) ProtoMessage() {}

func (x *DKGDealMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_network_protos_dkg_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DKGDealMessage.ProtoReflect.Descriptor instead.
func (*DKGDealMessage) Descriptor() ([]byte, []int) {
	return file_pkg_network_protos_dkg_messages_proto_rawDescGZIP(), []int{0}
}

func (x *DKGDealMessage) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *DKGDealMessage) GetDealData() []byte {
	if x != nil {
		return x.DealData
	}
	return nil
}

// DKGResponseMessage represents a DKG response message
type DKGResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderId     int32  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ResponseData []byte `protobuf:"bytes,2,opt,name=response_data,json=responseData,proto3" json:"response_data,omitempty"` // The response data, which is a serialized version of the pedersen.Response structure
}

func (x *DKGResponseMessage) Reset() {
	*x = DKGResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_network_protos_dkg_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DKGResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DKGResponseMessage) ProtoMessage() {}

func (x *DKGResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_network_protos_dkg_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DKGResponseMessage.ProtoReflect.Descriptor instead.
func (*DKGResponseMessage) Descriptor() ([]byte, []int) {
	return file_pkg_network_protos_dkg_messages_proto_rawDescGZIP(), []int{1}
}

func (x *DKGResponseMessage) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *DKGResponseMessage) GetResponseData() []byte {
	if x != nil {
		return x.ResponseData
	}
	return nil
}

var File_pkg_network_protos_dkg_messages_proto protoreflect.FileDescriptor

var file_pkg_network_protos_dkg_messages_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x6b, 0x67, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x64, 0x6b, 0x67, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x61, 0x6c, 0x67, 0x6f, 0x6c, 0x69, 0x6f,
	0x63, 0x64, 0x6d, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x4a, 0x0a, 0x0e, 0x44,
	0x4b, 0x47, 0x44, 0x65, 0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65,
	0x61, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x64,
	0x65, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x22, 0x56, 0x0a, 0x12, 0x44, 0x4b, 0x47, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x42,
	0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x65,
	0x6e, 0x6f, 0x76, 0x61, 0x74, 0x69, 0x78, 0x2f, 0x61, 0x6c, 0x67, 0x6f, 0x6c, 0x69, 0x6f, 0x63,
	0x64, 0x6d, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x3b, 0x6e, 0x65, 0x74, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_network_protos_dkg_messages_proto_rawDescOnce sync.Once
	file_pkg_network_protos_dkg_messages_proto_rawDescData = file_pkg_network_protos_dkg_messages_proto_rawDesc
)

func file_pkg_network_protos_dkg_messages_proto_rawDescGZIP() []byte {
	file_pkg_network_protos_dkg_messages_proto_rawDescOnce.Do(func() {
		file_pkg_network_protos_dkg_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_network_protos_dkg_messages_proto_rawDescData)
	})
	return file_pkg_network_protos_dkg_messages_proto_rawDescData
}

var file_pkg_network_protos_dkg_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_network_protos_dkg_messages_proto_goTypes = []interface{}{
	(*DKGDealMessage)(nil),     // 0: algoliocdm.network.DKGDealMessage
	(*DKGResponseMessage)(nil), // 1: algoliocdm.network.DKGResponseMessage
}
var file_pkg_network_protos_dkg_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_network_protos_dkg_messages_proto_init() }
func file_pkg_network_protos_dkg_messages_proto_init() {
	if File_pkg_network_protos_dkg_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_network_protos_dkg_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DKGDealMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_network_protos_dkg_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DKGResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_network_protos_dkg_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_network_protos_dkg_messages_proto_goTypes,
		DependencyIndexes: file_pkg_network_protos_dkg_messages_proto_depIdxs,
		MessageInfos:      file_pkg_network_protos_dkg_messages_proto_msgTypes,
	}.Build()
	File_pkg_network_protos_dkg_messages_proto = out.File
	file_pkg_network_protos_dkg_messages_proto_rawDesc = nil
	file_pkg_network_protos_dkg_messages_proto_goTypes = nil
	file_pkg_network_protos_dkg_messages_proto_depIdxs = nil
}
